CREATE DATABASE College;
USE College;
CREATE TABLE student (
    id INT PRIMARY KEY,
    name VARCHAR(50),
    age INT NOT NULL
);

INSERT INTO student VALUES(1,"AASHISH",20);
INSERT INTO student VALUES(2,"AASHUTOSH",18);
INSERT INTO student VALUES(3,"AASHIMA",22);
INSERT INTO student VALUES(4,"AASHISHDEEP",23);

SELECT * FROM student;